name: .NET Core (MacOS)

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: |
        dotnet tool install ElectronNET.CLI -g
        dotnet build --configuration Release
        electronize build /target osx
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: diademos.mac.tar.gz
        # Directory containing files to upload
        path: ./bin/desktop/
